services:
  - type: web
    name: quizbot-single
    runtime: python
    pythonVersion: 3.11.10
    envVars:
      TELEGRAM_BOT_TOKEN: "${TELEGRAM_BOT_TOKEN}"
      OWNER_TG_ID: "${OWNER_TG_ID}"
      REDIS_URL: "${REDIS_URL}"
      DB_PATH: "${DB_PATH}"
      APP_VERSION: "${APP_VERSION}"
    buildCommand: "pip install -r requirements.txt"
    startCommand: "honcho start -f Procfile"
